#+TITLE: OSM metadata description: the data behind the data
#+AUTHOR: Damien Garaud <damien.garaud@oslandia.com>, Raphaël Delhome <raphael.delhome@oslandia.com>

# Common introduction for articles of the OSM-data-quality series
At [Oslandia](http://oslandia.com/), we like workingg with Open Source tool
projects and handling Open (geospatial) Data. In this article series, we will
play with the [OpenStreetMap](https://www.openstreetmap.org/) (/OSM/) map and
subsequent data. Here comes the fifth article of this series, dedicated to the
extraction of OSM metadata starting from the OSM history data.

* Introduction...

Introduction of the article

* Extract OSM data history...

Develop the algorithm that aims to get the OSM history data, *i.e.* every
versions of every objects within the OSM API.

* Extract metadata features...

** Change set metadata...

Describe the features that will be used to characterize each change sets

** User metadata...

Describe the features that will be used to characterize each users
